extends: default

rules:
  line-length: disable
  braces:
    level: warning
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  infra/helm/
  services/member/node_modules/
  **/node_modules/
