apiVersion: v1
kind: Secret
metadata:
  name: nekocafe-secrets
  namespace: {{ include "nekocafe.namespace" . }}
type: Opaque
stringData:
  db-password: {{ .Values.postgres.password | quote }}
  reservation-db-url: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/nekocafe_reservation"
  member-db-url: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/nekocafe_member"
  redis-url-reservation: "redis://redis:6379/0"
  redis-url-member: "redis://redis:6379/1"
